language: python

python:
  - "3.7"

env:
  - DJANGO="Django>=2.2.0,<2.3.0"
  - DJANGO="Django>=3.0.0,<3.1.0"

install:
  - pip install -q $DJANGO
  - poetry install

script: poetry run pytest
